compressionLevel: mixed

enableGlobalCache: false

enableInlineHunks: true

yarnPath: .yarn/releases/yarn.cjs

packageExtensions:
  '@typescript-eslint/rule-tester@*':
    dependencies:
      '@typescript-eslint/parser': '^6.4.1'
