/* eslint-disable */
//prettier-ignore
module.exports = {
name: "@yarnpkg/plugin-tspace",
factory: function (require) {
"use strict";var plugin=(()=>{var l=Object.defineProperty;var k=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var j=Object.prototype.hasOwnProperty;var E=(o,t,s)=>t in o?l(o,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):o[t]=s;var m=(o=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(o,{get:(t,s)=>(typeof require<"u"?require:t)[s]}):o)(function(o){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+o+'" is not supported')});var $=(o,t)=>{for(var s in t)l(o,s,{get:t[s],enumerable:!0})},C=(o,t,s,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let e of P(t))!j.call(o,e)&&e!==s&&l(o,e,{get:()=>t[e],enumerable:!(r=k(t,e))||r.enumerable});return o};var J=o=>C(l({},"__esModule",{value:!0}),o);var w=(o,t,s)=>(E(o,typeof t!="symbol"?t+"":t,s),s);var M={};$(M,{TspaceCommand:()=>a,default:()=>O});var x=m("@yarnpkg/cli"),i=m("@yarnpkg/core"),f=m("fs/promises"),N=m("fs"),y=m("path");var h={compilerOptions:{paths:{}}};var a=class extends x.BaseCommand{async execute(){let t=await i.Configuration.find(this.context.cwd,this.context.plugins),{project:s}=await i.Project.find(t,this.context.cwd),r=(0,y.join)(this.context.cwd,"tsconfig.workspaces.json");return(await i.StreamReport.start({stdout:this.context.stdout,configuration:t},async d=>{await d.startTimerPromise("Update tsconfig workspaces",async()=>{var u;try{(0,N.existsSync)(r)||await(0,f.writeFile)(r,JSON.stringify(h,null,2));let c=await(0,f.readFile)(r).then(n=>JSON.parse(n.toString()));(u=c.compilerOptions).paths??(u.paths={});let S=c.compilerOptions.paths;s.workspaces.filter(n=>n.cwd!==this.context.cwd).forEach(({relativeCwd:n,manifest:{name:p}})=>{if(p){let g=p.scope?`@${p.scope}/${p.name}`:p.name;d.reportInfo(i.MessageName.UNNAMED,`Link ${g} -> ${n}`),S[g]=[n]}}),await(0,f.writeFile)(r,JSON.stringify(c,null,2))}catch(c){d.reportError(i.MessageName.UNNAMED,c.message)}})})).exitCode()}};w(a,"paths",[["tspace"]]);var O={commands:[a]};return J(M);})();
return plugin;
}
};
