name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install
        run: yarn install

      - name: Typecheck
        run: yarn ci typecheck
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
